### ISSUE TITLE
Failed to test on Mac systems

### ISSUE THREAD

**Issue by ecafkoob** [programatik29/rust-web-benchmarks#2] opened 2021-09-04 22:54 UTC
# osinfo:
ProductName:    macOS
ProductVersion: 11.5.2
BuildVersion:   20G95

kern.maxfilesperproc: 49152
kern.maxfiles: 98304

# result:
➜ echo "Results for hyper:" && rewrk -t 12 -c 300 -d 10s -h http://localhost:3000/

Results for hyper:
Beginning round 1...
Benchmarking 300 connections @ http://localhost:3000/ for 10 second(s)
failed to run benchmark round due to error: error combining results: connection closed

# use wrk it's ok:
➜ wrk -t12 -c400 -d30s --latency http://localhost:3000/
wrk                            http://localhost:3000/
Running 30s test @ http://localhost:3000/
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   808.44us  247.22us   3.95ms   72.97%
    Req/Sec    23.51k     9.67k  141.20k    79.11%
  Latency Distribution
     50%  819.00us
     75%    0.96ms
     90%    1.10ms
     99%    1.40ms
  7020424 requests in 30.10s, 589.18MB read
  Socket errors: connect 157, read 89, write 0, timeout 0
Requests/sec: 233235.83
Transfer/sec:     19.57MB

**Comment by programatik29** [comment] 2021-09-05 13:07
This is a [rewrk](https://github.com/ChillFish8/rewrk) problem. The problem is when an error occurs on one of the connections, program will return an error. So it isn't platform specific. I will open an issue there.

**Comment by programatik29** [comment] 2021-09-08 16:40
Can you try again with latest `rewrk`?

**Comment by ecafkoob** [comment] 2021-09-08 23:12
when i use `rewrk -t 12 -c 500 -d 10s -h http://localhost:3000/`  hyper crashed  with `Error: Os { code: 24, kind: Other, message: "Too many open files" }`.  `rewrk -t 12 -c 400 -d 10s -h http://localhost:3000/` is ok. wrk works well with 12 threads and 500 connections.

**Comment by programatik29** [comment] 2021-09-09 09:34
Might be related to [this](https://github.com/ChillFish8/rewrk/issues/18) which should be fixed with this [PR](https://github.com/ChillFish8/rewrk/pull/19).

**Comment by ecafkoob** [comment] 2021-09-09 14:03
<img width="705" alt="image" src="https://user-images.githubusercontent.com/12779980/132700358-23c954c4-3874-446c-a31f-407b1c339e01.png">
<img width="692" alt="image" src="https://user-images.githubusercontent.com/12779980/132700424-5a4e8c8e-3d56-404a-81a6-6c742f577984.png">



I want to know why there is such a big difference between URL and ip

**Closed as completed** 2021-09-13 05:18 UTC
